FROM mysql:8.0

COPY ./database/auth-db/schema.sql /docker-entrypoint-initdb.d/1_auth_schema.sql
COPY ./database/auth-db/indexes.sql /docker-entrypoint-initdb.d/2_auth_indexes.sql
COPY ./database/auth-db/seeds.sql   /docker-entrypoint-initdb.d/3_auth_seeds.sql
