"""initial schema

Revision ID: 4dd9c591f782
Revises: 
Create Date: 2026-07-22 01:18:34.717677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4dd9c591f782'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievement',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon_url', sa.String(length=255), nullable=True),
    sa.Column('xp_bonus', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_achievement_created_at'), 'achievement', ['created_at'], unique=False)
    op.create_index(op.f('ix_achievement_id'), 'achievement', ['id'], unique=False)
    op.create_index(op.f('ix_achievement_name'), 'achievement', ['name'], unique=False)
    op.create_index(op.f('ix_achievement_updated_at'), 'achievement', ['updated_at'], unique=False)
    op.create_table('files',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('owner_type', sa.Enum('PATIENT', 'USER', 'STORE_ITEM', 'ACHIEVEMENT', name='fileownertype'), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('stored_name', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('category', sa.Enum('AVATAR', 'AI_MEDIA', 'ITEM_IMAGE', 'ACHIEVEMENT_ICON', 'OTHER', name='filecategory'), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_files_category'), 'files', ['category'], unique=False)
    op.create_index(op.f('ix_files_created_at'), 'files', ['created_at'], unique=False)
    op.create_index(op.f('ix_files_id'), 'files', ['id'], unique=False)
    op.create_index(op.f('ix_files_mime_type'), 'files', ['mime_type'], unique=False)
    op.create_index(op.f('ix_files_owner_id'), 'files', ['owner_id'], unique=False)
    op.create_index(op.f('ix_files_updated_at'), 'files', ['updated_at'], unique=False)
    op.create_table('guardian',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('parentage', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guardian_created_at'), 'guardian', ['created_at'], unique=False)
    op.create_index(op.f('ix_guardian_name'), 'guardian', ['name'], unique=False)
    op.create_index(op.f('ix_guardian_parentage'), 'guardian', ['parentage'], unique=False)
    op.create_index(op.f('ix_guardian_updated_at'), 'guardian', ['updated_at'], unique=False)
    op.create_table('log_error',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('service', sa.String(length=100), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('stack_trace', sa.String(), nullable=True),
    sa.Column('level', sa.Enum('INFO', 'WARNING', 'ERROR', 'CRITICAL', name='loglevel'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_log_error_created_at'), 'log_error', ['created_at'], unique=False)
    op.create_index(op.f('ix_log_error_service'), 'log_error', ['service'], unique=False)
    op.create_index(op.f('ix_log_error_updated_at'), 'log_error', ['updated_at'], unique=False)
    op.create_index(op.f('ix_log_error_user_id'), 'log_error', ['user_id'], unique=False)
    op.create_table('login_acao',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('entity', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.Enum('CREATE', 'UPDATE', 'DELETE', 'LOGIN', 'LOGOUT', 'VIEW', name='auditaction'), nullable=False),
    sa.Column('old_data', sa.JSON(), nullable=True),
    sa.Column('new_data', sa.JSON(), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_login_acao_action'), 'login_acao', ['action'], unique=False)
    op.create_index(op.f('ix_login_acao_created_at'), 'login_acao', ['created_at'], unique=False)
    op.create_index(op.f('ix_login_acao_entity'), 'login_acao', ['entity'], unique=False)
    op.create_index(op.f('ix_login_acao_updated_at'), 'login_acao', ['updated_at'], unique=False)
    op.create_index(op.f('ix_login_acao_user_id'), 'login_acao', ['user_id'], unique=False)
    op.create_table('notification',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('receiver_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.Enum('ACHIEVEMENT', 'PROGRESS', 'SYSTEM', 'REMINDER', name='notificationtype'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('read_at', mysql.DATETIME(fsp=3), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_created_at'), 'notification', ['created_at'], unique=False)
    op.create_index(op.f('ix_notification_id'), 'notification', ['id'], unique=False)
    op.create_index(op.f('ix_notification_read'), 'notification', ['read'], unique=False)
    op.create_index(op.f('ix_notification_receiver_id'), 'notification', ['receiver_id'], unique=False)
    op.create_index(op.f('ix_notification_type'), 'notification', ['type'], unique=False)
    op.create_index(op.f('ix_notification_updated_at'), 'notification', ['updated_at'], unique=False)
    op.create_table('store_item',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('AVATAR', 'BACKGROUND', 'ACCESSORY', name='storeitemtype'), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_store_item_created_at'), 'store_item', ['created_at'], unique=False)
    op.create_index(op.f('ix_store_item_id'), 'store_item', ['id'], unique=False)
    op.create_index(op.f('ix_store_item_name'), 'store_item', ['name'], unique=False)
    op.create_index(op.f('ix_store_item_type'), 'store_item', ['type'], unique=False)
    op.create_index(op.f('ix_store_item_updated_at'), 'store_item', ['updated_at'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Uuid(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('STUDENT', 'TEACHER', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_created_at'), 'user', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_is_active'), 'user', ['is_active'], unique=False)
    op.create_index(op.f('ix_user_updated_at'), 'user', ['updated_at'], unique=False)
    op.create_table('world',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_world_created_at'), 'world', ['created_at'], unique=False)
    op.create_index(op.f('ix_world_id'), 'world', ['id'], unique=False)
    op.create_index(op.f('ix_world_is_active'), 'world', ['is_active'], unique=False)
    op.create_index(op.f('ix_world_order'), 'world', ['order'], unique=True)
    op.create_index(op.f('ix_world_updated_at'), 'world', ['updated_at'], unique=False)
    op.create_table('patient',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('guardian_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('current_level', sa.Integer(), nullable=False),
    sa.Column('total_xp', sa.Integer(), nullable=False),
    sa.Column('total_coins', sa.Integer(), nullable=False),
    sa.Column('sequence_days', sa.Integer(), nullable=False),
    sa.Column('interest', sa.JSON(), nullable=True),
    sa.Column('current_happiness', sa.Enum('HAPPY', 'SAD', 'NEUTRAL', 'ANGRY', name='happiness'), nullable=False),
    sa.Column('url_avatar', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['guardian_id'], ['guardian.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_created_at'), 'patient', ['created_at'], unique=False)
    op.create_index(op.f('ix_patient_current_happiness'), 'patient', ['current_happiness'], unique=False)
    op.create_index(op.f('ix_patient_current_level'), 'patient', ['current_level'], unique=False)
    op.create_index(op.f('ix_patient_guardian_id'), 'patient', ['guardian_id'], unique=False)
    op.create_index(op.f('ix_patient_id'), 'patient', ['id'], unique=False)
    op.create_index(op.f('ix_patient_name'), 'patient', ['name'], unique=False)
    op.create_index(op.f('ix_patient_updated_at'), 'patient', ['updated_at'], unique=False)
    op.create_table('stage',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('world_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('xp_reward', sa.Integer(), nullable=False),
    sa.Column('coin_reward', sa.Integer(), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['world_id'], ['world.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stage_created_at'), 'stage', ['created_at'], unique=False)
    op.create_index(op.f('ix_stage_id'), 'stage', ['id'], unique=False)
    op.create_index(op.f('ix_stage_updated_at'), 'stage', ['updated_at'], unique=False)
    op.create_index(op.f('ix_stage_world_id'), 'stage', ['world_id'], unique=False)
    op.create_table('ai_content',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('stage_id', sa.Uuid(), nullable=True),
    sa.Column('type', sa.Enum('STORY', 'IMAGE', 'EXERCISE', 'AUDIO', name='aicontenttype'), nullable=False),
    sa.Column('generated_text', sa.Text(), nullable=True),
    sa.Column('media_url', sa.Text(), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stage_id'], ['stage.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_content_created_at'), 'ai_content', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_content_id'), 'ai_content', ['id'], unique=False)
    op.create_index(op.f('ix_ai_content_patient_id'), 'ai_content', ['patient_id'], unique=False)
    op.create_index(op.f('ix_ai_content_stage_id'), 'ai_content', ['stage_id'], unique=False)
    op.create_index(op.f('ix_ai_content_type'), 'ai_content', ['type'], unique=False)
    op.create_index(op.f('ix_ai_content_updated_at'), 'ai_content', ['updated_at'], unique=False)
    op.create_table('patient_achievement',
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('achievement_id', sa.Uuid(), nullable=False),
    sa.Column('achieved_at', mysql.DATETIME(fsp=3), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievement.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('patient_id', 'achievement_id')
    )
    op.create_index(op.f('ix_patient_achievement_achievement_id'), 'patient_achievement', ['achievement_id'], unique=False)
    op.create_index(op.f('ix_patient_achievement_patient_id'), 'patient_achievement', ['patient_id'], unique=False)
    op.create_table('patient_clinical',
    sa.Column('patient_id', sa.String(length=36), nullable=True),
    sa.Column('clinical_rate', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('patient_id')
    )
    op.create_index(op.f('ix_patient_clinical_created_at'), 'patient_clinical', ['created_at'], unique=False)
    op.create_index(op.f('ix_patient_clinical_patient_id'), 'patient_clinical', ['patient_id'], unique=False)
    op.create_index(op.f('ix_patient_clinical_updated_at'), 'patient_clinical', ['updated_at'], unique=False)
    op.create_table('patient_inventory',
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('is_equipped', sa.Boolean(), nullable=False),
    sa.Column('acquired_at', mysql.DATETIME(fsp=3), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['store_item.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('patient_id', 'item_id')
    )
    op.create_index(op.f('ix_patient_inventory_item_id'), 'patient_inventory', ['item_id'], unique=False)
    op.create_index(op.f('ix_patient_inventory_patient_id'), 'patient_inventory', ['patient_id'], unique=False)
    op.create_table('patient_progress',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('stage_id', sa.Uuid(), nullable=False),
    sa.Column('highest_score', sa.Integer(), nullable=False),
    sa.Column('earned_stars', sa.Integer(), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_played_at', mysql.DATETIME(fsp=3), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stage_id'], ['stage.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id', 'stage_id', name='uq_patient_stage')
    )
    op.create_index(op.f('ix_patient_progress_created_at'), 'patient_progress', ['created_at'], unique=False)
    op.create_index(op.f('ix_patient_progress_id'), 'patient_progress', ['id'], unique=False)
    op.create_index(op.f('ix_patient_progress_patient_id'), 'patient_progress', ['patient_id'], unique=False)
    op.create_index(op.f('ix_patient_progress_stage_id'), 'patient_progress', ['stage_id'], unique=False)
    op.create_index(op.f('ix_patient_progress_updated_at'), 'patient_progress', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patient_progress_updated_at'), table_name='patient_progress')
    op.drop_index(op.f('ix_patient_progress_stage_id'), table_name='patient_progress')
    op.drop_index(op.f('ix_patient_progress_patient_id'), table_name='patient_progress')
    op.drop_index(op.f('ix_patient_progress_id'), table_name='patient_progress')
    op.drop_index(op.f('ix_patient_progress_created_at'), table_name='patient_progress')
    op.drop_table('patient_progress')
    op.drop_index(op.f('ix_patient_inventory_patient_id'), table_name='patient_inventory')
    op.drop_index(op.f('ix_patient_inventory_item_id'), table_name='patient_inventory')
    op.drop_table('patient_inventory')
    op.drop_index(op.f('ix_patient_clinical_updated_at'), table_name='patient_clinical')
    op.drop_index(op.f('ix_patient_clinical_patient_id'), table_name='patient_clinical')
    op.drop_index(op.f('ix_patient_clinical_created_at'), table_name='patient_clinical')
    op.drop_table('patient_clinical')
    op.drop_index(op.f('ix_patient_achievement_patient_id'), table_name='patient_achievement')
    op.drop_index(op.f('ix_patient_achievement_achievement_id'), table_name='patient_achievement')
    op.drop_table('patient_achievement')
    op.drop_index(op.f('ix_ai_content_updated_at'), table_name='ai_content')
    op.drop_index(op.f('ix_ai_content_type'), table_name='ai_content')
    op.drop_index(op.f('ix_ai_content_stage_id'), table_name='ai_content')
    op.drop_index(op.f('ix_ai_content_patient_id'), table_name='ai_content')
    op.drop_index(op.f('ix_ai_content_id'), table_name='ai_content')
    op.drop_index(op.f('ix_ai_content_created_at'), table_name='ai_content')
    op.drop_table('ai_content')
    op.drop_index(op.f('ix_stage_world_id'), table_name='stage')
    op.drop_index(op.f('ix_stage_updated_at'), table_name='stage')
    op.drop_index(op.f('ix_stage_id'), table_name='stage')
    op.drop_index(op.f('ix_stage_created_at'), table_name='stage')
    op.drop_table('stage')
    op.drop_index(op.f('ix_patient_updated_at'), table_name='patient')
    op.drop_index(op.f('ix_patient_name'), table_name='patient')
    op.drop_index(op.f('ix_patient_id'), table_name='patient')
    op.drop_index(op.f('ix_patient_guardian_id'), table_name='patient')
    op.drop_index(op.f('ix_patient_current_level'), table_name='patient')
    op.drop_index(op.f('ix_patient_current_happiness'), table_name='patient')
    op.drop_index(op.f('ix_patient_created_at'), table_name='patient')
    op.drop_table('patient')
    op.drop_index(op.f('ix_world_updated_at'), table_name='world')
    op.drop_index(op.f('ix_world_order'), table_name='world')
    op.drop_index(op.f('ix_world_is_active'), table_name='world')
    op.drop_index(op.f('ix_world_id'), table_name='world')
    op.drop_index(op.f('ix_world_created_at'), table_name='world')
    op.drop_table('world')
    op.drop_index(op.f('ix_user_updated_at'), table_name='user')
    op.drop_index(op.f('ix_user_is_active'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_created_at'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_store_item_updated_at'), table_name='store_item')
    op.drop_index(op.f('ix_store_item_type'), table_name='store_item')
    op.drop_index(op.f('ix_store_item_name'), table_name='store_item')
    op.drop_index(op.f('ix_store_item_id'), table_name='store_item')
    op.drop_index(op.f('ix_store_item_created_at'), table_name='store_item')
    op.drop_table('store_item')
    op.drop_index(op.f('ix_notification_updated_at'), table_name='notification')
    op.drop_index(op.f('ix_notification_type'), table_name='notification')
    op.drop_index(op.f('ix_notification_receiver_id'), table_name='notification')
    op.drop_index(op.f('ix_notification_read'), table_name='notification')
    op.drop_index(op.f('ix_notification_id'), table_name='notification')
    op.drop_index(op.f('ix_notification_created_at'), table_name='notification')
    op.drop_table('notification')
    op.drop_index(op.f('ix_login_acao_user_id'), table_name='login_acao')
    op.drop_index(op.f('ix_login_acao_updated_at'), table_name='login_acao')
    op.drop_index(op.f('ix_login_acao_entity'), table_name='login_acao')
    op.drop_index(op.f('ix_login_acao_created_at'), table_name='login_acao')
    op.drop_index(op.f('ix_login_acao_action'), table_name='login_acao')
    op.drop_table('login_acao')
    op.drop_index(op.f('ix_log_error_user_id'), table_name='log_error')
    op.drop_index(op.f('ix_log_error_updated_at'), table_name='log_error')
    op.drop_index(op.f('ix_log_error_service'), table_name='log_error')
    op.drop_index(op.f('ix_log_error_created_at'), table_name='log_error')
    op.drop_table('log_error')
    op.drop_index(op.f('ix_guardian_updated_at'), table_name='guardian')
    op.drop_index(op.f('ix_guardian_parentage'), table_name='guardian')
    op.drop_index(op.f('ix_guardian_name'), table_name='guardian')
    op.drop_index(op.f('ix_guardian_created_at'), table_name='guardian')
    op.drop_table('guardian')
    op.drop_index(op.f('ix_files_updated_at'), table_name='files')
    op.drop_index(op.f('ix_files_owner_id'), table_name='files')
    op.drop_index(op.f('ix_files_mime_type'), table_name='files')
    op.drop_index(op.f('ix_files_id'), table_name='files')
    op.drop_index(op.f('ix_files_created_at'), table_name='files')
    op.drop_index(op.f('ix_files_category'), table_name='files')
    op.drop_table('files')
    op.drop_index(op.f('ix_achievement_updated_at'), table_name='achievement')
    op.drop_index(op.f('ix_achievement_name'), table_name='achievement')
    op.drop_index(op.f('ix_achievement_id'), table_name='achievement')
    op.drop_index(op.f('ix_achievement_created_at'), table_name='achievement')
    op.drop_table('achievement')
    # ### end Alembic commands ###
