SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE IF NOT EXISTS Usuario (
    id VARCHAR(36) PRIMARY KEY DEFAULT (UUID()),
    email VARCHAR(255) UNIQUE NOT NULL,
    senha_hash VARCHAR(255) NOT NULL,
    nome VARCHAR(255) NOT NULL,
    cargo ENUM('professor', 'medico', 'administrador') NOT NULL DEFAULT 'professor',
    esta_ativo BOOLEAN NOT NULL DEFAULT TRUE,
    ultimo_login DATETIME(3),
    criado_em DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3),
    atualizado_em DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)
);

SET FOREIGN_KEY_CHECKS = 1;
